language: python

matrix:
    include:
      - python: 3.5
      - python: 3.6
      - python: 3.7
        dist: xenial

os: osx

install:
    - python setup.py install

after_success:
    - coveralls
